channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=23.3.1
- pip:
  - mlflow==2.15.0
  - cloudpickle==3.0.0
  - numpy==1.26.1
  - psutil==5.9.5
  - scikit-learn==1.4.2
  - scipy==1.11.3
name: mlflow-env
