channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=23.3.1
- pip:
  - mlflow==2.15.0
  - cloudpickle==3.0.0
  - ipywidgets==8.1.3
  - matplotlib==3.7.5
  - numpy==1.26.1
  - pandas==2.1.2
  - pickleshare==0.7.5
  - scipy==1.11.3
  - seaborn==0.13.2
  - statsmodels==0.14.0
name: mlflow-env
